version: "2.3"
services:
  mysql:
    restart: always
    image: mysql:5.7.19
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  ballerina:
    image: lpastor/ballerina-cn:v3
    ports:
      - "9990:9090"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9090"]
      interval: 10s
      timeout: 120s
      start_period: 40s
      retries: 10
    links:
      - mysql
