version: "2.3"
services:
  mysql:
    restart: always
    image: mysql:5.7.19
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  am-analytics:
    image: docker.wso2.com/wso2am-analytics-worker:2.6.0
    ports:
      - "9091:9091"
      - "9444:9444"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9091"]
      interval: 10s
      timeout: 120s
      start_period: 80s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./apim-analytics:/home/wso2carbon/wso2-config-volume
  is-as-km:
    image: docker.wso2.com/wso2is-km:5.7.0
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9445"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 15
    depends_on:
      mysql:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
    volumes:
      - ./is-as-km:/home/wso2carbon/wso2-config-volume
    ports:
      - "9765:9765"
      - "9445:9445"
  api-manager:
    image: docker.wso2.com/wso2am:2.6.0
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9443"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
      is-as-km:
        condition: service_healthy
    volumes:
      - ./apim:/home/wso2carbon/wso2-config-volume
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
  gw-pizza:
    image: wso2/wso2micro-gw:3.0.1
    ports:
      - "9075:9095"
      - "9070:9090"
    environment:
      project: pizza
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9095"]
      interval: 10s
      timeout: 120s
      start_period: 40s
      retries: 10
    volumes:
      - ./gw-pizza/balx:/home/exec/
      - ./gw-pizza/conf:/home/ballerina/conf/
