version: "2.3"
services:
  mysql:
    restart: always
    image: mysql:5.7.19
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  gw-user:
    image: wso2/wso2micro-gw:3.0.1
    ports:
      - "9095:9095"
      - "9090:9090"
    environment:
      project: get-user
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9095"]
      interval: 10s
      timeout: 120s
      start_period: 40s
      retries: 10
    volumes:
      - ./gw-user/balx:/home/exec/
      - ./gw-user/conf:/home/ballerina/conf/
  py-app:
    image: lpastor/cn2app:latest
    ports:
      - "5055:5055"
      - "8281:8280"
      - "8244:8243"
    environment:
      HOSTNAME: py.com
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5055"]
      interval: 10s
      timeout: 120s
      start_period: 40s
      retries: 10
    depends_on:
      gw-user:
        condition: service_healthy
    links:
      - gw-user
    volumes:
      - ./app:/app/
  py-api:
    image: lpastor/cn2api:latest
    ports:
      - "5000:5000"
    environment:
      HOSTNAME: py.com
    links:
      - mysql
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
      interval: 10s
      timeout: 120s
      start_period: 40s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api:/app/
